title: Hi, I'm Rob Unger!
description: > # this means to ignore newlines until "baseurl:"
  Just another Microsoft 365 blog covering Identity, Security and more 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robunger.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rob Unger # add your name
author-img: rob-unger.png # add your photo
about-author: I'm a senior technical consultant, working for a leading UK Microsoft partner. I focus is mostly Identity and Security. All views and opinions are my own # add description
social-twitter: r0bUn # add your Twitter handle
social-github: r0bu # add your Github handle
social-linkedin: rob-u # add your Linkedin handle
#social-facebook: # add your Facebook handle
#social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-163496078-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
